/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#3f6653",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "secondary": "#3e6750",
        "secondary-container": "#bdeacd",
        "on-tertiary-fixed-variant": "#0e5138",
        "tertiary-fixed": "#b1f0ce",
        "inverse-surface": "#2e3132",
        "on-primary-container": "#86af99",
        "on-surface-variant": "#414844",
        "on-background": "#191c1d",
        "surface-container": "#edeeef",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#a5d0b9",
        "tertiary": "#002d1c",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#002114",
        "on-error-container": "#93000a",
        "background": "#f8f9fa",
        "on-secondary-fixed-variant": "#264f39",
        "surface-bright": "#f8f9fa",
        "on-secondary-container": "#426b54",
        "on-primary-fixed-variant": "#274e3d",
        "on-secondary-fixed": "#002112",
        "on-primary-fixed": "#002114",
        "surface": "#f8f9fa",
        "surface-container-low": "#f3f4f5",
        "secondary-fixed-dim": "#a4d1b4",
        "inverse-primary": "#a5d0b9",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed": "#c0edd0",
        "tertiary-fixed-dim": "#95d4b3",
        "tertiary-container": "#00452e",
        "primary": "#012d1d",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "surface-dim": "#d9dadb",
        "primary-container": "#1b4332",
        "primary-fixed": "#c1ecd4",
        "outline": "#717973",
        "on-tertiary-container": "#75b393",
        "outline-variant": "#c1c8c2",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "xs": "8px",
        "gutter": "24px",
        "lg": "40px",
        "base": "4px",
        "container-max": "1280px",
        "sm": "16px",
        "md": "24px",
        "xl": "64px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
