// <auto-generated />
using System;
using InvoiSys.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvoiSys.Infrastructure.Database.Migrations
{
    [DbContext(typeof(InvoiSysDbContext))]
    partial class InvoiSysDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvoiSys.Domain.Entities.ComunicadoExportado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CaminhoArquivo")
                        .HasColumnType("text")
                        .HasColumnName("caminho_arquivo");

                    b.Property<string>("Conteudo")
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("formato");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gerado_em");

                    b.Property<string>("GeradoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("gerado_por");

                    b.Property<string>("Publico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("publico");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("VersaoComunicadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("versao_comunicado_id");

                    b.HasKey("Id")
                        .HasName("pk_comunicados_exportados");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_comunicados_exportados_release_id");

                    b.HasIndex("VersaoComunicadoId")
                        .HasDatabaseName("ix_comunicados_exportados_versao_comunicado_id");

                    b.ToTable("comunicados_exportados", null, t =>
                        {
                            t.HasCheckConstraint("ck_comunicados_exportados_formato", "formato IN ('markdown','html','pdf')");

                            t.HasCheckConstraint("ck_comunicados_exportados_publico", "publico IN ('cliente','comercial','suporte','interno')");
                        });
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.DestaqueHero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icone");

                    b.Property<int>("Ordem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("ordem");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_destaques_hero");

                    b.HasIndex("Ativo", "Ordem")
                        .HasDatabaseName("ix_destaques_hero_ativo_ordem");

                    b.ToTable("destaques_hero", (string)null);
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.ExecucaoPipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluido_em");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<DateTimeOffset>("IniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciado_em");

                    b.Property<string>("ModeloLlm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo_llm");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_execucoes_pipeline");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_execucoes_pipeline_release_id");

                    b.ToTable("execucoes_pipeline", null, t =>
                        {
                            t.HasCheckConstraint("ck_execucoes_pipeline_status", "status IN ('iniciada','concluida','falhou')");
                        });
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.HistoriaJira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chave");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DescricaoTecnica")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_tecnica");

                    b.Property<string[]>("Labels")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("labels");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("TextoReleaseNote")
                        .HasColumnType("text")
                        .HasColumnName("texto_release_note");

                    b.Property<string>("TipoIssue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_issue");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_historias_jira");

                    b.HasIndex("ReleaseId", "Chave")
                        .IsUnique()
                        .HasDatabaseName("ix_historias_jira_release_id_chave");

                    b.ToTable("historias_jira", (string)null);
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.ItemComunicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("categoria");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Incluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("incluido");

                    b.Property<string>("MotivoExclusao")
                        .HasColumnType("text")
                        .HasColumnName("motivo_exclusao");

                    b.Property<string[]>("Origens")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("origens");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.Property<string>("TextoEditadoManualmente")
                        .HasColumnType("text")
                        .HasColumnName("texto_editado_manualmente");

                    b.Property<Guid>("VersaoComunicadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("versao_comunicado_id");

                    b.HasKey("Id")
                        .HasName("pk_itens_comunicado");

                    b.HasIndex("Origens")
                        .HasDatabaseName("ix_itens_comunicado_origens");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Origens"), "GIN");

                    b.HasIndex("VersaoComunicadoId")
                        .HasDatabaseName("ix_itens_comunicado_versao_comunicado_id");

                    b.ToTable("itens_comunicado", null, t =>
                        {
                            t.HasCheckConstraint("ck_itens_comunicado_categoria", "categoria IN ('nova_funcionalidade','melhoria','correcao','outros')");
                        });
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChaveJira")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chave_jira");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_releases");

                    b.HasIndex("ChaveJira")
                        .IsUnique()
                        .HasDatabaseName("ix_releases_chave_jira");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_releases_status");

                    b.ToTable("releases", null, t =>
                        {
                            t.HasCheckConstraint("ck_releases_status", "status IN ('pendente','processando','aguardando_revisao','aprovado','falhou')");
                        });
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("release_manager")
                        .HasColumnName("papel");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.VersaoComunicado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("MotivoReprovacao")
                        .HasColumnType("text")
                        .HasColumnName("motivo_reprovacao");

                    b.Property<string>("Publico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("publico");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("ResumoExecutivo")
                        .HasColumnType("text")
                        .HasColumnName("resumo_executivo");

                    b.Property<DateTimeOffset?>("RevisadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revisado_em");

                    b.Property<string>("RevisadoPor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("revisado_por");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TituloExecutivo")
                        .HasColumnType("text")
                        .HasColumnName("titulo_executivo");

                    b.HasKey("Id")
                        .HasName("pk_versoes_comunicado");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_versoes_comunicado_status");

                    b.HasIndex("ReleaseId", "Publico")
                        .IsUnique()
                        .HasDatabaseName("ix_versoes_comunicado_release_id_publico");

                    b.ToTable("versoes_comunicado", null, t =>
                        {
                            t.HasCheckConstraint("ck_versoes_comunicado_motivo_reprovacao", "status <> 'reprovado' OR motivo_reprovacao IS NOT NULL");

                            t.HasCheckConstraint("ck_versoes_comunicado_publico", "publico IN ('cliente','comercial','suporte','interno')");

                            t.HasCheckConstraint("ck_versoes_comunicado_status", "status IN ('aguardando_revisao','aprovado','reprovado')");
                        });
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.ComunicadoExportado", b =>
                {
                    b.HasOne("InvoiSys.Domain.Entities.Release", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comunicados_exportados_releases_release_id");

                    b.HasOne("InvoiSys.Domain.Entities.VersaoComunicado", null)
                        .WithMany()
                        .HasForeignKey("VersaoComunicadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comunicados_exportados_versoes_comunicado_versao_comunicado");
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.ExecucaoPipeline", b =>
                {
                    b.HasOne("InvoiSys.Domain.Entities.Release", null)
                        .WithMany("Execucoes")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_execucoes_pipeline_releases_release_id");
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.HistoriaJira", b =>
                {
                    b.HasOne("InvoiSys.Domain.Entities.Release", null)
                        .WithMany("Historias")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historias_jira_releases_release_id");
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.ItemComunicado", b =>
                {
                    b.HasOne("InvoiSys.Domain.Entities.VersaoComunicado", null)
                        .WithMany("Itens")
                        .HasForeignKey("VersaoComunicadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itens_comunicado_versoes_comunicado_versao_comunicado_id");
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.VersaoComunicado", b =>
                {
                    b.HasOne("InvoiSys.Domain.Entities.Release", null)
                        .WithMany("Versoes")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_versoes_comunicado_releases_release_id");
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.Release", b =>
                {
                    b.Navigation("Execucoes");

                    b.Navigation("Historias");

                    b.Navigation("Versoes");
                });

            modelBuilder.Entity("InvoiSys.Domain.Entities.VersaoComunicado", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
